# Generated by Django 5.2.8 on 2026-01-31 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_pushtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushtoken",
            name="token",
            field=models.CharField(max_length=255),
        ),
    ]
