# Generated by Django 5.2.8 on 2026-03-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_chatthread_direct_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("comment", "Comment"),
                    ("message", "Message"),
                    ("trail_start", "Trail Start"),
                    ("trail_share", "Trail Share"),
                    ("trail_comment", "Trail Comment"),
                    ("trail_reply", "Trail Reply"),
                ],
                max_length=20,
            ),
        ),
    ]
