# Generated by Django 5.2.5 on 2026-02-27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(blank=True, max_length=140)),
                (
                    "status",
                    models.CharField(
                        choices=[("recording", "Recording"), ("completed", "Completed")],
                        default="recording",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("followers", "Followers-only"), ("private", "Private")],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("start_lat", models.FloatField(blank=True, null=True)),
                ("start_lng", models.FloatField(blank=True, null=True)),
                ("end_lat", models.FloatField(blank=True, null=True)),
                ("end_lng", models.FloatField(blank=True, null=True)),
                ("distance_m", models.FloatField(default=0)),
                ("final_comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time", "-id"],
                "indexes": [
                    models.Index(fields=["user", "status", "-start_time"], name="trailbook_t_user_st_ebec07_idx"),
                    models.Index(fields=["status", "visibility", "-start_time"], name="trailbook_t_status_6be5a3_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrailMoment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("moment_type", models.CharField(choices=[("photo", "Photo"), ("video", "Video"), ("note", "Note"), ("comment", "Comment")], max_length=20)),
                ("text", models.TextField(blank=True, null=True)),
                ("media_file", models.FileField(blank=True, null=True, upload_to="trailbook/")),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moments",
                        to="trailbook.trailentry",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
                "indexes": [
                    models.Index(fields=["trail", "recorded_at"], name="trailbook_t_trail_i_9385a4_idx"),
                    models.Index(fields=["moment_type"], name="trailbook_t_moment__5f5115_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrailPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("accuracy", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="trailbook.trailentry",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
                "indexes": [models.Index(fields=["trail", "recorded_at"], name="trailbook_t_trail_i_295e4f_idx")],
            },
        ),
    ]
