# Generated by Django 5.2.8 on 2026-02-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trailbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailpoint",
            name="cell_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="mcc_mnc",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="mno",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="network_type",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="rsrp",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="rsrq",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="rssi_dbm",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="signal_sampled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="sinr",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailpoint",
            name="tac",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
