# Generated by Django 5.2.8 on 2026-03-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trailbook",
            "0002_trailpoint_cell_id_trailpoint_mcc_mnc_trailpoint_mno_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trailentry",
            name="path_geometry",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
