# Generated by Django 5.2.8 on 2026-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trailbook", "0003_trailentry_path_geometry"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailmoment",
            name="caption",
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
