# Generated by Django 5.2.8 on 2026-03-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trailbook", "0004_trailmoment_caption"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailentry",
            name="share_scope",
            field=models.CharField(
                choices=[("full", "Entire trail"), ("moments", "Moments only")],
                default="full",
                max_length=20,
            ),
        ),
    ]
