# Generated by Django 5.2.8 on 2026-03-05 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_chatthread_direct_key"),
        ("trailbook", "0005_trailentry_share_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailPlaybackShareRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_ids", models.JSONField(blank=True, default=list)),
                ("group_ids", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("status_note", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_playback_share_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="playback_share_requests",
                        to="trailbook.trailentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trail", "status", "-created_at"],
                        name="trailbook_p_trail_s_b0d4a8_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TrailShare",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "share_scope",
                    models.CharField(
                        choices=[("full", "Entire trail"), ("moments", "Moments only")],
                        default="full",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shared_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_shares_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_shares",
                        to="accounts.chatthread",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_shares_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="trailbook.trailentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["trail", "target_user"],
                        name="trailbook_s_trail_u_8aa3f1_idx",
                    ),
                    models.Index(
                        fields=["trail", "target_group"],
                        name="trailbook_s_trail_g_3a11c2_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        check=(
                            models.Q(target_user__isnull=False, target_group__isnull=True)
                            | models.Q(target_user__isnull=True, target_group__isnull=False)
                        ),
                        name="trailbook_share_single_target_ck",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_user__isnull", False)),
                        fields=("trail", "target_user"),
                        name="trailbook_share_trail_user_uniq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("target_group__isnull", False)),
                        fields=("trail", "target_group"),
                        name="trailbook_share_trail_group_uniq",
                    ),
                ],
            },
        ),
    ]
