# Generated by Django 5.2.8 on 2026-03-05 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_chatthread_direct_key"),
        ("trailbook", "0006_trailshare_and_playback_share_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="trailshare",
            name="trailbook_share_single_target_ck",
        ),
        migrations.AddConstraint(
            model_name="trailshare",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_user__isnull", False), ("target_group__isnull", True)
                    ),
                    models.Q(
                        ("target_user__isnull", True), ("target_group__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="trailbook_share_single_target_ck",
            ),
        ),
    ]
