# Generated by Django 5.2.8 on 2026-03-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "trailbook",
            "0007_remove_trailshare_trailbook_share_single_target_ck_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trailplaybacksharerequest",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailplaybacksharerequest",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trailplaybacksharerequest",
            name="output_video",
            field=models.FileField(
                blank=True, null=True, upload_to="trailbook/playback_exports/"
            ),
        ),
        migrations.AddField(
            model_name="trailplaybacksharerequest",
            name="progress_percent",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trailplaybacksharerequest",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
