# Generated by Django 5.2.8 on 2026-03-10 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trailbook", "0009_trailmomentcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrailMomentLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "moment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="trailbook.trailmoment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trail_moment_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["moment", "created_at"],
                        name="trailbook_l_moment_59b2b4_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="trailbook_l_user_9e2f13_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("moment", "user"),
                        name="trailbook_like_moment_user_uniq",
                    )
                ],
            },
        ),
    ]
